### ISSUE TITLE
PUSHER_SUBSCRIPTIONS in init function

### ISSUE THREAD

**Issue by peyterkim** [jamiebikies/ember-pusher#13]
hello again, sorry for asking so many questions on this thread. i appreciate that you are answering them!
One more question though (hopefully)!

I have dynamic channel names based off of each user which I'm defining in the init() function of my listening controller like so:
`init: function(){var channel = this.get('pusher.connection').subscribe('channel_'+user_id);
		PUSHER_SUBSCRIPTIONS: {channel: ['message_received', 'offer_received']}
	},`

but it seems like defining subscriptions doesn't work like it should. Could you clarify on how it should be subscriptions should be defined in the init?

**Comment by jcope2013** [comment]
+1

**Comment by jamiebikies** [comment]
Hey, there's actually a bit about this in the README... https://github.com/jamiebikies/ember-pusher#how-do-i-use-this-thing
