### ISSUE TITLE
multiple uses of a controller

### ISSUE THREAD

**Issue by jess** [jamiebikies/ember-pusher#14]
I'm not sure if I'm doing something wrong or if this is a bug?

I have a controller that gets used rendered multiple times on a page.

For example:

```
// (Emblem js syntax)
each question.comments itemController="CommentsComment"
        partial "comments/comment"
```

When I extend the CommentsComment controller with EmberPusher.Bindings, subscribe to a channel and push an event, my action / event gets called every time the controller is called in the template. So if my question has 5 comments, my action gets called 5 times.

Am I doing something wrong? Thanks in advance for the help.

**Comment by mmun** [comment]
Each creates a temporary item controller for item in the array, so it makes sense that the action fires for each item controller. Maybe you mean to put the bindings on an array controller?
