### ISSUE TITLE
Dashed in Channel Names

### ISSUE THREAD

**Issue by malrase** [jamiebikies/ember-pusher#16]
Pusher requires some channels to have dashes in their names. Notably, "private-" prefixed channel names. Unfortunately, with the `PUSHER_SUBSCRIPTIONS` being a JS literal that we can't modify, it won't allow us to use dashed names.

So, there is no way to subscribe to "private-messages" channel in a controller. :(

Patch coming to add an option called `dasherizeChannel` to the `PUSHER_OPTS` that allows camel-cased channel names to be automatically renamed to the dasherized version.

**Comment by jamiebikies** [comment]
I'm confused....

`PUSHER_SUBSCRIPTIONS: { 'my-channel-name' : 'foo-event' }`

or...

```javascript
init: function() {
  PUSHER_SUBSCRIPTIONS = {}
  PUSHER_SUBSCRIPTIONS['my-channel-name'] = ['foo-event']
}
```

Works perfectly for this case ;)
