### ISSUE TITLE
How to put my session token to be passed in PUSHER_OPTS for private channels?

### ISSUE THREAD

**Issue by joshuairl** [jamiebikies/ember-pusher#18]
I've placed my PUSHER_OPTS in environment.js

```javascript
APP: {
      LOG_TRANSITIONS:          true,
      LOG_TRANSITIONS_INTERNAL: true,
      PUSHER_OPTS: {
        key: 'my_key',
        connection: {
          authEndpoint: '/api/me/pusher',
          auth: {
            headers: {
              'accept': 'application/json; version=1'
            }
          }
        }
      }
    }
```

But how do I get headers['authorization'] in there since it's a dynamic value based on the session?
Any ideas?

**Comment by variousred** [comment]
wondering abou this as well

**Comment by jcope2013** [comment]
wondering same thing, any solution?

**Comment by jamiebikies** [comment]
Have you tried putting the setting of `PUSHER_OPTS` in an initializer that runs before ember pusher's initializer? This is something we should flesh out a real solution for.

**Comment by variousred** [comment]
@jamiebikies was there a real solution for this?
