### ISSUE TITLE
Wiring the subscriptions after init.

### ISSUE THREAD

**Issue by barelyknown** [jamiebikies/ember-pusher#20]
I'm wiring up subscriptions on a `Controller` that does not have what it needs during `init` to define the key for the channel. So, I added a `wireSubscriptions` function that is called by the `Route` once it has what it needs during `setupController`.

`app/routes/organization/buyer/loads.js`
```
import Ember from 'ember';

export default Ember.Route.extend(AuthenticatedRouteMixin, {
  model: function() {
    return this.modelFor('organization/buyer').get('loads');
  },

  setupController: function(controller, model) {
    this._super(controller, model);
    var buyer = this.modelFor('organization/buyer');
    controller.PUSHER_SUBSCRIPTIONS['buyers-' + buyer.get('id')] = ['upsert-load']
    controller.wireSubscriptions();
  }
});
```

`app/controllers/organization/buyer/loads.js`
```
import Ember from 'ember';
import { Bindings } from 'ember-pusher/bindings';

export default Ember.ArrayController.extend(Bindings, {
  PUSHER_SUBSCRIPTIONS: {},

  wireSubscriptions: function() {
    var target = this;
    Object.keys(target.PUSHER_SUBSCRIPTIONS).forEach(function (channelName) {
      var events = target.PUSHER_SUBSCRIPTIONS[channelName];
      target.pusher.wire(target, channelName, events);
    });
  },

  actions: {
    upsertLoad: function(data) {
      this.store.pushPayload(data);
    }
  }
});
```

Two questions:

1. Should the `wireSubscriptions` function be extracted from `init` in the library so that it can be called when necessary?
2. Is there anything about this situation that feels unusual? Am I missing something?

**Comment by jamiebikies** [comment]
I'm confused....why are you doing all this? There's some content in the README that talks about how to accomplish what you're doing.

If you have dynamic channels/events you just make sure you've defined `PUSHER_SUBSCRIPTIONS` before calling `this._super()`. Thats it :)

```javascript
init: function() {
  PUSHER_SUBSCRIPTIONS = ['foo-channel' : 'bar-event']';
  this._super();
}```

**Comment by barelyknown** [comment]
Because I don't know the `eventName` until after `init`.

**Comment by jamiebikies** [comment]
Gotcha, so what you use in that case, is just `wire`.

```javascript
needs: ['pusher'],
events: ['foo-event', 'bar-event'],

channelNameChanged: function() {
  this.get('controllers.pusher').wire(this, this.get('channelName'), this.get('events'));
}.observes('channelName')
```

**Comment by barelyknown** [comment]
OK. That's pretty close to what I did - thanks for clarifying that I wasn't missing something.

**Comment by jamiebikies** [comment]
No problem, I've updated the example a bit! :metal:
