### ISSUE TITLE
Question: using bower to manage test dependencies

### ISSUE THREAD

**Issue by elskwid** [jamiebikies/ember-pusher#21]
Hi there,

I am spinning up the development environment so I can start contributing back as it seems like several of the issues are things we're going to need. While doing so I noticed that the test dependencies are vendored.

Would you be open to a pull request that used bower to manage these dependencies?

I feel like it would make it easier to try out new dep versions while developing and potentially allow testing against multiple version of Ember.

Thank you very much for creating `ember-pusher` we'll be wiring it up today and it provides a huge boost to our app to be able to do so quickly.

**Comment by jamiebikies** [comment]
Hey @elskwid, glad to have the help! Certainly pulling in dependencies in a better way is desirable. This library was written at a time when I had to hand-roll everything.

Pulling in deps for the test harness with bower seems reasonable.

**Comment by elskwid** [comment]
Neat! Thanks for the quick reply ... now where did I put that VM?

**Comment by jamiebikies** [comment]
I'm working ember-cli'izing ember-pusher making this a moot point.

**Comment by elskwid** [comment]
Ah, well, let me know if you need a hand. I'll poke around on some of the other stuff if you like.

**Comment by elskwid** [comment]
@jamiebikies given that you're making some changes is it okay to create pull requests for other things? I'd love to take a stab at a few of the issues.

**Comment by jamiebikies** [comment]
Yeah go for it! What were you thinking?

**Comment by elskwid** [comment]
I was looking at #1 and #6. We will need #1 sooner rather than later and I have time allocated to work on it. If you'll have me.

**Comment by jamiebikies** [comment]
#1 I've wanted to work on for a long time now!
