### ISSUE TITLE
If I use dynamic channels and come from before model, how can I set the PUSHER_SUBSCRIPTIONS?

### ISSUE THREAD

**Issue by JeskTop** [jamiebikies/ember-pusher#25]
Route:
```
export default Ember.Route.extend({
  beforeModel() {
    Account.find().then(user => {
      this.set('user', user);
    });

    return Company.find().then(company => {
      this.set('company', company);
    });
  },
  ...
  setupController(controller, model) {
    ...
    controller.set('company', this.get('company'));
    controller.set('user', this.get('user'));
  }
});
```
My channels look like `${company.id}_channel`, and the `use` different authority have different `event`, example:
```
if(user.isAdmin) {
   event: ['admin_event']
} else {
   event: ['customer_event']
}
```
How can I set it in my controller? Thanks.

**Comment by trevorrjohn** [comment]
@JeskTop did you find a nice solution for this?

**Comment by jamiebikies** [comment]
Hey, there are instructions on how to do this in [README](https://github.com/jamiebikies/ember-pusher#how-do-i-use-this-thing)

> If you have dynamic channel names or events, you can totally just construct your PUSHER_SUBSCRIPTIONS hash in init() of your controller (note: be sure to call this._super() afterwards).
