### ISSUE TITLE
Cannot read property 'subscribe' of null

### ISSUE THREAD

**Issue by marcqualie** [jamiebikies/ember-pusher#28]
I may be missing something obvious, so apologies if that's the case but I can't seem to figure out how to get this Addon to work correctly (latest master build).

I've installed the addon, injected the service controller bindings but I get the following error:

```
Error while processing route: index Cannot read property 'subscribe' of null TypeError: Cannot read property 'subscribe' of null
  at ConnectChannel
  at wire
```

After looking through the source code it appears `service.init()` is being triggered, but `service.setup()` is not, which is where `this.pusher` is defined. How do I call `service.setup()` from my application with the required configuration?

**Comment by mmun** [comment]
@marcqualie You call setup in an application instance initializer. It takes the same arguments as the Pusher constructor. See: https://github.com/jamiebikies/ember-pusher/blob/master/addon/services/pusher.js#L55-L59

**Comment by mmun** [comment]
```js
export function initialize(instance) {
  let pusherService = instance.container.lookup('service:pusher');
  pusherService.setup(YOUR_KEY, extraPusherOptions);
  });
}

export default {
  name: 'ember-pusher',
  initialize: initialize
};
```

**Comment by marcqualie** [comment]
@mmun thanks for the very quick reply, that worked perfectly. It was my lack of service understanding that I needed to add my own initializer to my application as it existed in your app/initializers folder.

**Comment by ZackMattor** [comment]
Shouldn't this be mentioned in the README?...

**Comment by mmun** [comment]
Yes, I'm not using pusher right now so I don't have time to update it. Happy to review any PRs that bring the addon closer to 1.0. Please make an issue if you'd like to discuss something before implementing.
