### ISSUE TITLE
Connection status and socket id

### ISSUE THREAD

**Issue by SebastianSzturo** [jamiebikies/ember-pusher#31]
I tried the example from the ```README.md``` to get notified on connection status changes and socket changes, but it doesn't really work for me. I see many different socket reconnects and socket id changes in my chrome dev tools but the console.log command never gets fired. 

![screen shot 2015-10-30 at 16 40 27](https://cloud.githubusercontent.com/assets/2699745/10850306/1dfcf1b8-7f25-11e5-8c2a-df4fd9189ef4.png)

Is anyone using connection status observes and give me some tips how to get them to work?

**Comment by jamiebikies** [comment]
Hm, I am using them, and they work...what do your actions look like?
