### ISSUE TITLE
Deprecation Warning Ember  > 2.1.x

### ISSUE THREAD

**Issue by ZackMattor** [jamiebikies/ember-pusher#32]
Ember's initializers have a new API for object lookups (more public now..)

http://emberjs.com/deprecations/v2.x/#toc_ember-applicationinstance-container

<img width="1205" alt="screen shot 2015-12-15 at 11 35 38 pm" src="https://cloud.githubusercontent.com/assets/552776/11832277/c27a70ca-a384-11e5-912a-d111cf12d31c.png">

https://github.com/jamiebikies/ember-pusher/blob/master/tests/dummy/app/instance-initializers/ember-pusher.js#L2

**Comment by jamiebikies** [comment]
Fixed!
