### ISSUE TITLE
Ember 2.2 TypeError: container.lookup is not a function     at Object.Ember.Application.initializer.initialize [as initialize] (ember-pusher.js:296

### ISSUE THREAD

**Issue by marcodemoja** [jamiebikies/ember-pusher#34]
I'm trying to use the module with ember 2.2 and ember-data 2.2 andI receive the same error even using ember-cli-pusher.
Initially, following the doc, I thought problem was because the 2 arguments into the initialize method:
https://guides.emberjs.com/v2.2.0/applications/dependency-injection/

so I tried to remove the container args replacing all the container.register and container.lookup occurrences in application.register and application.lookup but the problem still remains.

**Comment by jamiebikies** [comment]
Hi @marcodemoja I have updated the README's install/usage instructions. Closing the issue.
