### ISSUE TITLE
Import EmberPusher

### ISSUE THREAD

**Issue by iorrah** [jamiebikies/ember-pusher#38]
Hi all,

**Migration process:**

As the ember-cli-pusher 0.1.2 (NPM) package and the ember-pusher 0.1.1 (bower) component were pointed as deprecated, I am migrating to the ember-pusher 0.1.0 (NPM) project.

As my app is still configured according to the old packages, I was experiencing the following issue...

... when importing the ember-pusher library into my controller like this:

```
`import { Controller } from 'ember-pusher/controller'`;
`import { Bindings } from 'ember-pusher/bindings'`;
`import { ClientEvents } from 'ember-pusher/client_events'`;
```

To solve the problem, I added ember-browserify ^1.1.9 in my package.json and updated the controller imports to the following:

```
`import Ember from 'ember'`;
`import { EmberPusher } from 'npm:ember-pusher'`;
```

**The issue:**

When I try to access my app on the browser, I get the following error message:

`initializer.js:11 Uncaught Include Pusher before EmberPusher`

I have been researching for a solution but had no success. Can someone help me?

Thank you all.

**Comment by jamiebikies** [comment]
Hi @iorrah, did you ever resolve this? I have updated the install and usage instructions... https://github.com/jamiebikies/ember-pusher#install
