### ISSUE TITLE
Old releases deleted?

### ISSUE THREAD

**Issue by davidgovea** [jamiebikies/ember-pusher#39]
Hello - what is the status of this repository?

Our bower.json files included:
```
    "ember-pusher": "0.1.1",
```
But now bower cannot find these versions.

Why did this happen? Will semver practices be maintained in the future?

**Comment by davidgovea** [comment]
Apologies - looks like those releases are actually coming from https://github.com/ivanvotti/ember-pusher-component. Bit confused by the multitude of repositories..

**Comment by jamiebikies** [comment]
Hi @davidgovea those release were coming from this. Please install ember pusher according to: 
https://github.com/jamiebikies/ember-pusher#install
