### ISSUE TITLE
Uncaught Error: Could not find module `npm:pusher-js` imported from `new-app/services/pusher`

### ISSUE THREAD

**Issue by csprocket777** [jamiebikies/ember-pusher#42]
I've just installed this addon in a fresh app and am getting the following error in my console:

```
Uncaught Error: Could not find module `npm:pusher-js` imported from `lti-game-library/services/pusher`
```

Ember-cli version: 2.6.2

I have installed Ember-browserify and pusher-js per the instructions.

**Comment by csprocket777** [comment]
RTFM closer. :)

**Comment by jamiebikies** [comment]
:)

**Comment by jeffrey008** [comment]
Hi I'm having the same problem now and I don't know which part of the manual I am missing. Can someone please point it me?

**Comment by jeffrey008** [comment]
Alright got it. Install ember-browserify. #RTFM
