### ISSUE TITLE
Add tags / new release

### ISSUE THREAD

**Issue by mattboldt** [jamiebikies/ember-pusher#44]
There have been some fixes on master after v1.1.0. Could you update the releases?

**Comment by robclancy** [comment]
This seems abandoned?

**Comment by jamiebikies** [comment]
It's not - I can get the release out. I've just been swamped.

**Comment by joegaudet** [comment]
Any news on this?

**Comment by jamiebikies** [comment]
https://github.com/jamiebikies/ember-pusher/releases/tag/v1.1.1

**Comment by joegaudet** [comment]
Thanks Jamie!!! We've loved working with the module so far, made adding realtime a sinch!

Will you be publishing it to NPM as well?
