### ISSUE TITLE
No longer supported?

### ISSUE THREAD

**Issue by hbrysiewicz** [jamiebikies/ember-pusher#47]
It seems that this addon has not been upgraded to support newer versions of babel/ember.

We have made a new package which has _nearly_ a 1:1 api match to this addon so that current users of this addon can upgrade. [Check it out here!](https://github.com/starshot-tech/ember-pusher-js)

**Comment by jamiebikies** [comment]
Why didn't you just contribute back to the original repository and instead just take the API design?
