### ISSUE TITLE
Ember CLI support

### ISSUE THREAD

**Issue by mmun** [jamiebikies/ember-pusher#9]
We should consider rewriting this plugin as en ember-cli addon and publishing it to http://www.emberaddons.com/.

**Comment by ivanvotti** [comment]
https://github.com/ivanvotti/ember-cli-pusher
https://github.com/ivanvotti/ember-pusher-component

**Comment by mmun** [comment]
@ivanvotti Awesome! we'll check it out.

**Comment by vasilakisfil** [comment]
Any update on that?

**Comment by vasilakisfil** [comment]
I guess that's it: https://github.com/ivanvotti/ember-cli-pusher
